# Generated by Django 3.0.3 on 2020-02-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fancybar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praatscript',
            name='icon',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
