# Generated by Django 3.0.3 on 2020-02-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fancybar', '0002_auto_20200222_1452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PraatScript',
            new_name='PraatScripts',
        ),
    ]
