# Generated by Django 3.0.3 on 2020-02-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fancybar', '0003_auto_20200222_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='praatscripts',
            options={'verbose_name_plural': 'Praat scripts'},
        ),
    ]
