# Generated by Django 3.0.4 on 2020-03-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fancybar', '0004_auto_20200225_1126'),
        ('fancybar', '0004_auto_20200224_0927'),
    ]

    operations = [
    ]
