# Generated by Django 3.0.4 on 2020-03-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_pony',
            field=models.CharField(default='Tree Hugger', max_length=1024),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.IntegerField(choices=[(1, 'Princess Luna'), (2, 'King Sombra'), (3, 'Shining Armor'), (4, 'Pinkie Pie')], default=1),
        ),
    ]
