# Generated by Django 3.0.4 on 2020-03-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(path='/home/user/Documents/giphouse/CLST-2020/equestria/media/'),
        ),
    ]
