# Generated by Django 3.0.4 on 2020-03-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(path='U:\\Django\\CLST\\CLST-2020\\equestria\\media/'),
        ),
    ]
