# Generated by Django 3.0.4 on 2020-03-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200325_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(path='/Users/lars/Documents/GitHub/CLST-2020/equestria/media/'),
        ),
    ]
