# Generated by Django 3.0.4 on 2020-04-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0003_auto_20200328_1110"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="usage",
            field=models.CharField(default="transscript", max_length=30),
            preserve_default=False,
        ),
    ]
