# Generated by Django 3.0.4 on 2020-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200319_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filetype',
            field=models.CharField(default='text/plain', max_length=30),
            preserve_default=False,
        ),
    ]
