# Generated by Django 3.0.4 on 2020-04-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200403_1216'),
        ('upload', '0004_file_usage'),
    ]

    operations = [
    ]
