# Generated by Django 3.0.4 on 2020-03-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_file_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(path='/home/user/dox/giphouse/CLST-2020/equestria/media/'),
        ),
    ]
