# Generated by Django 3.0.4 on 2020-03-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20200320_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(path='/Users/lars/Documents/GitHub/CLST-2020/equestria/media/'),
        ),
    ]
