# Generated by Django 3.0.4 on 2020-04-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200330_1500'),
        ('upload', '0005_merge_20200408_0749'),
    ]

    operations = [
    ]
