# Generated by Django 3.0.4 on 2020-04-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_merge_20200408_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(path='/home/pi/Documents/SoftEng/CLST-2020/equestria/media/'),
        ),
    ]
