# Generated by Django 3.0.4 on 2020-04-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20200418_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
    ]
