# Generated by Django 3.0.4 on 2020-04-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_file_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(path='/home/david/Desktop/CLST-2020/CLST-2020/equestria/media/'),
        ),
    ]
