# Generated by Django 3.0.4 on 2020-04-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20200419_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(path='/Users/lars/Documents/GitHub/CLST-2020/equestria/media/'),
        ),
    ]
