# Generated by Django 3.0.4 on 2020-05-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20200421_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
