# Generated by Django 3.0.4 on 2020-03-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_runner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputfile',
            name='output_file',
            field=models.FilePathField(path='./'),
        ),
        migrations.AlterField(
            model_name='script',
            name='output_file_or_directory',
            field=models.FilePathField(allow_folders=True, blank=True, help_text='Additional outputs generated', path='./'),
        ),
        migrations.AlterField(
            model_name='script',
            name='primary_output_file',
            field=models.FilePathField(blank=True, help_text='The file to be used for live output', path='./'),
        ),
        migrations.AlterField(
            model_name='script',
            name='script_file',
            field=models.FilePathField(blank=True, help_text='specify either a file to execute', path='./'),
        ),
    ]
