# Generated by Django 3.0.3 on 2020-03-06 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script_runner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['name'], 'verbose_name_plural': 'Scripts'},
        ),
        migrations.RenameField(
            model_name='script',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='script',
            name='path',
        ),
        migrations.AddField(
            model_name='script',
            name='command',
            field=models.CharField(blank=True, help_text='or a command to execute', max_length=1024),
        ),
        migrations.AddField(
            model_name='script',
            name='output_file_or_directory',
            field=models.FilePathField(allow_folders=True, blank=True, help_text='Additional outputs generated', path='scripts/'),
        ),
        migrations.AddField(
            model_name='script',
            name='primary_output_file',
            field=models.FilePathField(blank=True, help_text='The file to be used for live output', path='scripts/'),
        ),
        migrations.AddField(
            model_name='script',
            name='script_file',
            field=models.FilePathField(blank=True, help_text='specify either a file to execute', path='scripts/'),
        ),
        migrations.AlterField(
            model_name='script',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome glyph to show if image is unavailable', max_length=4),
        ),
        migrations.AlterField(
            model_name='script',
            name='img',
            field=models.ImageField(blank=True, help_text='Thumbnail to symbolize script', upload_to='script_img'),
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('output_file', models.FilePathField(path='scripts/')),
                ('description', models.TextField(max_length=32768)),
                ('associated_script', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='script_runner.Script')),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('required', models.BooleanField(default=False)),
                ('short_flag', models.CharField(blank=True, max_length=16)),
                ('long_flag', models.CharField(blank=True, max_length=512)),
                ('arg_type', models.IntegerField()),
                ('description', models.TextField(max_length=32768)),
                ('associated_script', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='script_runner.Script')),
            ],
            options={
                'verbose_name_plural': 'Arguments',
                'ordering': ['name'],
            },
        ),
    ]
