# Generated by Django 3.0.3 on 2020-03-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_runner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Arguments',
            },
        ),
        migrations.CreateModel(
            name='ScriptA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='script',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome glyph to show if image is unavailable', max_length=4),
        ),
        migrations.AlterField(
            model_name='script',
            name='img',
            field=models.ImageField(blank=True, help_text='Thumbnail to symbolize script', upload_to='script_img'),
        ),
        migrations.AlterField(
            model_name='script',
            name='path',
            field=models.FileField(blank=True, default='', upload_to='script'),
        ),
    ]
