# Generated by Django 3.0.4 on 2020-03-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script_runner', '0002_auto_20200314_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['name'], 'verbose_name_plural': 'Processes'},
        ),
        migrations.RemoveField(
            model_name='script',
            name='command',
        ),
        migrations.RemoveField(
            model_name='script',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='script',
            name='output_file_or_directory',
        ),
        migrations.RemoveField(
            model_name='script',
            name='primary_output_file',
        ),
        migrations.RemoveField(
            model_name='script',
            name='script_file',
        ),
        migrations.AddField(
            model_name='process',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='script_runner.Script'),
        ),
        migrations.AddField(
            model_name='script',
            name='hostname',
            field=models.URLField(default='localhost:8080'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='clam_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='script',
            name='description',
            field=models.TextField(blank=True, max_length=32768),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='script_runner.Process')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InputTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=1024)),
                ('format', models.CharField(max_length=1024)),
                ('label', models.CharField(max_length=1024)),
                ('extension', models.CharField(max_length=32)),
                ('optional', models.BooleanField()),
                ('unique', models.BooleanField()),
                ('accept_archive', models.BooleanField()),
                ('corresponding_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='script_runner.Profile')),
            ],
            options={
                'verbose_name': 'Input template',
                'verbose_name_plural': 'Input templates',
                'ordering': ['id'],
            },
        ),
    ]
