# Generated by Django 3.0.4 on 2020-03-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_runner', '0006_merge_20200318_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
