# Generated by Django 3.0.4 on 2020-03-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_runner', '0007_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='output_file',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
