# Generated by Django 3.0.7 on 2020-06-07 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scripts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('preset', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(0, 'Boolean'), (1, 'Static'), (2, 'String'), (3, 'Choice'), (4, 'Text'), (5, 'Integer'), (6, 'Float')])),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('hostname', models.URLField()),
                ('description', models.TextField(blank=True, max_length=32768)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Scripts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TextParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter')),
            ],
        ),
        migrations.CreateModel(
            name='StringParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=2048, null=True)),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter')),
            ],
        ),
        migrations.CreateModel(
            name='StaticParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=2048, null=True)),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Script')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clam_id', models.CharField(default=None, max_length=256, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Uploading files to CLAM'), (2, 'Running'), (3, 'Waiting for download from CLAM'), (4, 'Downloading files from CLAM'), (5, 'Finished'), (-1, 'Error'), (-2, 'Error while downloading files from CLAM')], default=0)),
                ('folder', models.FilePathField(allow_files=False, allow_folders=True, path=scripts.models.user_data_folder_path)),
                ('script', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Script')),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('fa_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_script', to='scripts.Script')),
                ('g2p_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g2p_script', to='scripts.Script')),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('message', models.CharField(max_length=16384)),
                ('index', models.PositiveIntegerField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Process')),
            ],
        ),
        migrations.CreateModel(
            name='IntegerParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter')),
            ],
        ),
        migrations.CreateModel(
            name='InputTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=1024)),
                ('format', models.CharField(max_length=1024)),
                ('label', models.CharField(max_length=1024)),
                ('mime', models.CharField(default='text/plain', max_length=1024)),
                ('extension', models.CharField(max_length=32)),
                ('optional', models.BooleanField()),
                ('unique', models.BooleanField()),
                ('accept_archive', models.BooleanField()),
                ('corresponding_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Profile')),
            ],
            options={
                'verbose_name': 'Input template',
                'verbose_name_plural': 'Input templates',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FloatParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Choice')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='corresponding_choice_parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.ChoiceParameter'),
        ),
        migrations.CreateModel(
            name='BooleanParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(blank=True, default=False, null=True)),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter')),
            ],
        ),
        migrations.AddField(
            model_name='baseparameter',
            name='corresponding_script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Script'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('folder', models.FilePathField(allow_files=False, allow_folders=True, path=scripts.models.user_data_folder_path)),
                ('current_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Process')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Pipeline')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('access_project', 'Access project')],
                'unique_together': {('name', 'user')},
            },
        ),
    ]
