# Generated by Django 3.0.3 on 2020-02-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.IntegerField()),
                ('input_file', models.FilePathField(path='/home/micheldeboer/Documents/SoftEng/CLST-2020/equestria')),
                ('output_file', models.FilePathField(path='/home/micheldeboer/Documents/SoftEng/CLST-2020/equestria')),
                ('executing', models.BooleanField(default=False)),
            ],
        ),
    ]
