# Generated by Django 3.0.4 on 2020-03-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('clam_id', models.CharField(blank=True, max_length=256)),
                ('output_path', models.CharField(default='output/error.log', max_length=512)),
                ('status', models.IntegerField(default=0)),
                ('output_file', models.CharField(blank=True, default=None, max_length=512, null=True)),
            ],
            options={
                'verbose_name_plural': 'Processes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('hostname', models.URLField()),
                ('img', models.ImageField(blank=True, help_text='Thumbnail to symbolize script', upload_to='script_img')),
                ('description', models.TextField(blank=True, max_length=32768)),
                ('forced_alignment_script', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Scripts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Process')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='process',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Script'),
        ),
        migrations.CreateModel(
            name='InputTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=1024)),
                ('format', models.CharField(max_length=1024)),
                ('label', models.CharField(max_length=1024)),
                ('mime', models.CharField(default='text/plain', max_length=1024)),
                ('extension', models.CharField(max_length=32)),
                ('optional', models.BooleanField()),
                ('unique', models.BooleanField()),
                ('accept_archive', models.BooleanField()),
                ('corresponding_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Profile')),
            ],
            options={
                'verbose_name': 'Input template',
                'verbose_name_plural': 'Input templates',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('input_file', models.FilePathField(path='uploads/')),
                ('description', models.TextField(max_length=32768)),
                ('associated_process', models.ManyToManyField(default=None, to='scripts.Process')),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('required', models.BooleanField(default=False)),
                ('short_flag', models.CharField(blank=True, max_length=16)),
                ('long_flag', models.CharField(blank=True, max_length=512)),
                ('arg_type', models.IntegerField(choices=[(1, 'User specified file'), (2, 'User specified string'), (3, 'User specified boolean'), (4, 'User specified integer')])),
                ('description', models.TextField(max_length=32768)),
                ('associated_script', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scripts.Script')),
            ],
            options={
                'verbose_name_plural': 'Arguments',
                'ordering': ['name'],
            },
        ),
    ]
