# Generated by Django 3.0.5 on 2020-05-20 19:00

from django.db import migrations, models
import scripts.models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterField(
            model_name='process',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path=scripts.models.user_data_folder_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path=scripts.models.user_data_folder_path),
        ),
    ]
