# Generated by Django 3.0.4 on 2020-03-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='script',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
