# Generated by Django 3.0.3 on 2020-03-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20200304_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='input_file',
            field=models.FilePathField(default='', path='/home/user/dox/giphouse/CLST-2020/equestria'),
        ),
        migrations.AlterField(
            model_name='process',
            name='output_file',
            field=models.FilePathField(default='', path='/home/user/dox/giphouse/CLST-2020/equestria'),
        ),
    ]
