# Generated by Django 3.0.4 on 2020-03-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_runner', '0003_auto_20200315_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtemplate',
            name='mime',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
