# Generated by Django 3.0.3 on 2020-03-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_auto_20200305_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='input_file',
            field=models.FilePathField(default='', path='/Users/lars/Documents/GitHub/CLST-2020/equestria'),
        ),
        migrations.AlterField(
            model_name='process',
            name='output_file',
            field=models.FilePathField(default='', path='/Users/lars/Documents/GitHub/CLST-2020/equestria'),
        ),
    ]
