# Generated by Django 3.0.4 on 2020-04-09 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scripts', '0005_remove_process_status_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('folder', models.FilePathField(allow_files=False, allow_folders=True, path='/Users/lars/Documents/GitHub/CLST-2020/equestria/userdata')),
            ],
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'Processes'},
        ),
        migrations.RemoveField(
            model_name='process',
            name='name',
        ),
        migrations.RemoveField(
            model_name='process',
            name='output_file',
        ),
        migrations.RemoveField(
            model_name='process',
            name='output_path',
        ),
        migrations.RemoveField(
            model_name='script',
            name='forced_alignment_script',
        ),
        migrations.RemoveField(
            model_name='script',
            name='img',
        ),
        migrations.DeleteModel(
            name='InputFile',
        ),
        migrations.AddField(
            model_name='project',
            name='current_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Process'),
        ),
        migrations.AddField(
            model_name='project',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Pipeline'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='fa_script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_script', to='scripts.Script'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='g2p_script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g2p_script', to='scripts.Script'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'user')},
        ),
    ]
