# Generated by Django 3.0.4 on 2020-03-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script_runner', '0005_auto_20200318_1340'),
        ('script_runner', '0004_script_forced_alignment_script'),
    ]

    operations = [
    ]
