# Generated by Django 3.0.4 on 2020-04-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_auto_20200409_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, default='/', path='/Users/lars/Documents/GitHub/CLST-2020/equestria/userdata'),
            preserve_default=False,
        ),
    ]
