# Generated by Django 3.0.4 on 2020-04-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_auto_20200410_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='clam_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Uploading files to CLAM'), (2, 'Running'), (3, 'Waiting for download from CLAM'), (4, 'Downloading files from CLAM'), (5, 'Finished'), (-1, 'Error'), (-2, 'Error while downloading files from CLAM')], default=0),
        ),
    ]
