# Generated by Django 3.0.4 on 2020-04-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0009_auto_20200411_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/home/pi/Documents/SoftEng/CLST-2020/equestria/userdata'),
        ),
        migrations.AlterField(
            model_name='project',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/home/pi/Documents/SoftEng/CLST-2020/equestria/userdata'),
        ),
    ]
