# Generated by Django 3.0.4 on 2020-04-21 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0011_auto_20200419_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='process',
        ),
        migrations.AddField(
            model_name='profile',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Script'),
        ),
        migrations.AlterField(
            model_name='process',
            name='clam_id',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/Users/lars/Documents/GitHub/CLST-2020/equestria/userdata'),
        ),
        migrations.AlterField(
            model_name='project',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/Users/lars/Documents/GitHub/CLST-2020/equestria/userdata'),
        ),
    ]
