# Generated by Django 3.0.4 on 2020-04-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0012_auto_20200421_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/home/david/Desktop/CLST-2020/CLST-2020/equestria/userdata'),
        ),
        migrations.AlterField(
            model_name='project',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/home/david/Desktop/CLST-2020/CLST-2020/equestria/userdata'),
        ),
    ]
