# Generated by Django 3.0.4 on 2020-04-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0013_baseparameter_booleanparameter_choiceparameter_stringparameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booleanparameter',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='choiceparameter',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='stringparameter',
            name='relation',
        ),
        migrations.AddField(
            model_name='baseparameter',
            name='type',
            field=models.IntegerField(choices=[(0, 'Boolean'), (1, 'Static'), (2, 'String'), (3, 'Choice'), (4, 'Text'), (5, 'Integer'), (6, 'Float')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='booleanparameter',
            name='base',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter'),
        ),
        migrations.AddField(
            model_name='choiceparameter',
            name='base',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter'),
        ),
        migrations.AddField(
            model_name='stringparameter',
            name='base',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter'),
        ),
        migrations.AlterField(
            model_name='booleanparameter',
            name='value',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='stringparameter',
            name='value',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.CreateModel(
            name='TextParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(null=True)),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter')),
            ],
        ),
        migrations.CreateModel(
            name='IntegerParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter')),
            ],
        ),
        migrations.CreateModel(
            name='FloatParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corresponding_choice_parameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.ChoiceParameter')),
            ],
        ),
        migrations.AlterField(
            model_name='choiceparameter',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Choice'),
        ),
    ]
