# Generated by Django 3.0.4 on 2020-04-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0014_auto_20200422_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='value',
            field=models.CharField(default='bla', max_length=2048),
            preserve_default=False,
        ),
    ]
