# Generated by Django 3.0.4 on 2020-04-22 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0015_choice_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceparameter',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.Choice'),
        ),
    ]
