# Generated by Django 3.0.4 on 2020-04-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0016_auto_20200422_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanparameter',
            name='value',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='floatparameter',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integerparameter',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stringparameter',
            name='value',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='textparameter',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StaticParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=2048, null=True)),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.BaseParameter')),
            ],
        ),
    ]
