# Generated by Django 3.0.4 on 2020-04-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0017_auto_20200422_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseparameter',
            options={'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
        migrations.AlterField(
            model_name='baseparameter',
            name='type',
            field=models.IntegerField(choices=[(0, 'Boolean'), (1, 'Static'), (2, 'String'), (3, 'Choice'), (4, 'Text'), (5, 'Integer'), (6, 'Float')], default=0),
            preserve_default=False,
        ),
    ]
