# Generated by Django 3.0.5 on 2020-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0018_auto_20200423_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='C:\\Users\\Valentijn Albertus\\Documents\\School\\Software Engineering\\CLST-2020\\equestria\\userdata'),
        ),
        migrations.AlterField(
            model_name='project',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='C:\\Users\\Valentijn Albertus\\Documents\\School\\Software Engineering\\CLST-2020\\equestria\\userdata'),
        ),
    ]
