# Generated by Django 3.0.5 on 2020-05-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0019_auto_20200513_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('access_project', 'Access project'),)},
        ),
        migrations.AlterField(
            model_name='process',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/home/david/Desktop/CLST-2020/CLST-2020/equestria/userdata'),
        ),
        migrations.AlterField(
            model_name='project',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/home/david/Desktop/CLST-2020/CLST-2020/equestria/userdata'),
        ),
    ]
