# Generated by Django 3.0.3 on 2020-03-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('script_file', models.FilePathField(blank=True, help_text='specify either a file to execute', path='scripts/')),
                ('command', models.CharField(blank=True, help_text='or a command to execute', max_length=1024)),
                ('primary_output_file', models.FilePathField(blank=True, help_text='The file to be used for live output', path='outputs/')),
                ('output_file_or_directory', models.FilePathField(allow_folders=True, blank=True, help_text='Additional outputs generated', path='outputs/')),
                ('img', models.ImageField(blank=True, help_text='Thumbnail to symbolize script', upload_to='script_img')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome glyph to show if image is unavailable', max_length=4)),
                ('description', models.TextField(max_length=32768)),
            ],
            options={
                'verbose_name_plural': 'Scripts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('output_file', models.FilePathField(path='scripts/')),
                ('description', models.TextField(max_length=32768)),
                ('associated_script', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='script_runner.Script')),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('required', models.BooleanField(default=False)),
                ('short_flag', models.CharField(blank=True, max_length=16)),
                ('long_flag', models.CharField(blank=True, max_length=512)),
                ('arg_type', models.IntegerField(choices=[(1, 'User specified file'), (2, 'User specified string'), (3, 'User specified boolean'), (4, 'User specified integer')])),
                ('description', models.TextField(max_length=32768)),
                ('associated_script', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='script_runner.Script')),
            ],
            options={
                'verbose_name_plural': 'Arguments',
                'ordering': ['name'],
            },
        ),
    ]
